name: autism
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas>=0.21
  - jupyter
  - matplotlib
  - scikit-learn>=0.19
  - seaborn
  - nilearn
  - keras
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
