name: autism
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy<1.20
  - pandas>=0.21
  - jupyter
  - matplotlib
  - scikit-learn>=0.19,<=0.21
  - seaborn
  - nilearn
  - cloudpickle
  - pip
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/0.2.1
